# Basic
title: 湾区脱单指南
author: Vivian Wong
subtitle: 为理工男生全面订制脱单方案
# welcome_message: 
# description: description
creator: 湾区脱单指南

url: bayareafindlove.github.io

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# Navigation buttons in the front page.
nav:
    - {title: 首页, url: 'https://bayareafindlove.wixsite.com/home', target: '_blank'} # if new window, add target
    
# The blog button should not be removed.
blog_button:
    title: Blog

# Pagination
plugins: 
   - jekyll-paginate
   - jekyll-seo-tag
   - jekyll-sitemap
paginate: 10
paginate_path: "page/:num/"

