# Basic
title: 湾区脱单指南
author: Vivian Wong
subtitle: 为理工男生全面订制脱单方案
welcome_message: Welcome 
description: 面向理工科男生的最强脱单神器。代码有对象而你也可以有。全面订制恋爱约会脱单方案、恋爱咨询。微信视频面对面解疑答惑。
creator: 湾区脱单指南

url: https://bayareafindlove.github.io

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# Navigation buttons in the front page.
nav:
    - {title: 进入首页, url: ''} # if new window, add target。 i changed side-panel.html to make button absolute path to wix site
    
# The blog button should not be removed.
blog_button:
    title: Blog

# Pagination
plugins: 
   - jekyll-paginate
   - jekyll-seo-tag
   - jekyll-sitemap
paginate: 10
paginate_path: "page/:num/"

